parameters:
#    ongoing_sitemap.example.class: Ongoing\SitemapBundle\Example

services:
#    ongoing_sitemap.example:
#        class: %ongoing_sitemap.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
